# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Windows MSVC C++
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    strategy:
      matrix:
        cmake-generator:
          - Visual Studio 16 2019
          - Visual Studio 15 2017
        include:
          - cmake-generator: Visual Studio 16 2019
            os: windows-2019
          - cmake-generator: Visual Studio 15 2017
            os: windows-2016
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: CMake
        shell: cmd
        run: |
          mkdir build\cpp
          cmake ^
            -G "${{ matrix.cmake-generator }}" ^
            -A x64 ^
            -DARROW_USE_GLOG=OFF ^
            -DARROW_WITH_LZ4=OFF ^
            -DARROW_WITH_ZLIB=OFF ^
            -DCMAKE_INSTALL_PREFIX=install ^
            -S cpp ^
            -B build\cpp
      - name: Install
        shell: cmd
        run: |
          cmake --build build\cpp --config Debug --target Install
